In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import timm
import glob

In [2]:
checkpoint_paths = []
checkpoint_path = '/home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/28-Covid19-PlainCNN/0810_195001/checkpoint_37_fold3_.pth'
state_dict_path = '/home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/28-Covid19-PlainCNN/0810_195001/checkpoint_63_fold1.pt'

In [3]:
check_point = torch.load(checkpoint_path)

In [4]:
torch.save(check_point['state_dict'], state_dict_path)

In [4]:
# checkpoint_paths = glob.glob('/home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/19-Covid19-PlainCNN/0807_080220/*.pth')
# for checkpoint_path in checkpoint_paths:
#     state_dict_path = checkpoint_path[:-1]
#     print(state_dict_path, checkpoint_path)
#     check_point = torch.load(checkpoint_path)
#     torch.save(check_point['state_dict'], state_dict_path)

/home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/19-Covid19-PlainCNN/0807_080220/checkpoint_35_fold1.pt /home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/19-Covid19-PlainCNN/0807_080220/checkpoint_35_fold1.pth
/home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/19-Covid19-PlainCNN/0807_080220/checkpoint_12_fold1.pt /home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/19-Covid19-PlainCNN/0807_080220/checkpoint_12_fold1.pth
/home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/19-Covid19-PlainCNN/0807_080220/checkpoint_4_fold1.pt /home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/19-Covid19-PlainCNN/0807_080220/checkpoint_4_fold1.pth
/home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/19-Covid19-PlainCNN/0807_080220/checkpoint_7_fold1.pt /home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/19-Covid19-PlainCNN/0807_080220/checkpoint_7_fold1.pth
/home/ha

In [31]:
x = torch.load('/media/sonnh/AICOVIDVN/saved1/models/63-Covid19-Eff_b7/checkpoint/checkpoint_48_fold3_.pth') 

In [32]:
x.keys()

dict_keys(['arch', 'epoch', 'state_dict', 'monitor_best', 'config'])

In [33]:
# x['state_dict']
from collections import OrderedDict
x_ = OrderedDict()
for key in x['state_dict']:
    new_key = key[7:]
    x_[new_key] = x['state_dict'][key]

In [34]:
x['state_dict'] = x_

In [35]:
torch.save(x, '/media/sonnh/AICOVIDVN/saved1/models/63-Covid19-Eff_b7/checkpoint/checkpoint_48_fold3.pth')

In [10]:
x = torch.load('/media/sonnh/AICOVIDVN/saved1/models/63-Covid19-Eff_b7/checkpoint/checkpoint_30_fold1.pth') 
x['state_dict'].keys()

odict_keys(['spectrogram_extractor.stft.conv_real.weight', 'spectrogram_extractor.stft.conv_imag.weight', 'logmel_extractor.melW', 'bn0.weight', 'bn0.bias', 'bn0.running_mean', 'bn0.running_var', 'bn0.num_batches_tracked', 'backbone.conv_stem.weight', 'backbone.bn1.weight', 'backbone.bn1.bias', 'backbone.bn1.running_mean', 'backbone.bn1.running_var', 'backbone.bn1.num_batches_tracked', 'backbone.blocks.0.0.conv_dw.weight', 'backbone.blocks.0.0.bn1.weight', 'backbone.blocks.0.0.bn1.bias', 'backbone.blocks.0.0.bn1.running_mean', 'backbone.blocks.0.0.bn1.running_var', 'backbone.blocks.0.0.bn1.num_batches_tracked', 'backbone.blocks.0.0.se.conv_reduce.weight', 'backbone.blocks.0.0.se.conv_reduce.bias', 'backbone.blocks.0.0.se.conv_expand.weight', 'backbone.blocks.0.0.se.conv_expand.bias', 'backbone.blocks.0.0.conv_pw.weight', 'backbone.blocks.0.0.bn2.weight', 'backbone.blocks.0.0.bn2.bias', 'backbone.blocks.0.0.bn2.running_mean', 'backbone.blocks.0.0.bn2.running_var', 'backbone.blocks.0.0.b

# test

In [23]:
from torch.optim.swa_utils import AveragedModel, SWALR

In [1]:
checkpoint_path = 'saved1/models/51-Covid19-CNN14/0815_154408/model_best_fold3'
# state_dict_path = '/home/hana/sonnh/covidaivn/Covid19_Cough_Classification/saved/models/28-Covid19-PlainCNN/0810_195001/checkpoint_63_fold1.pt'

In [4]:
check_point = torch.load(checkpoint_path)

In [10]:
check_point['state_dict']

OrderedDict([('n_averaged', tensor(0)),
             ('module.base.spectrogram_extractor.stft.conv_real.weight',
              tensor([[[ 0.0000e+00,  3.7649e-05,  1.5059e-04,  ...,  3.3881e-04,
                         1.5059e-04,  3.7649e-05]],
              
                      [[ 0.0000e+00,  3.7646e-05,  1.5055e-04,  ...,  3.3858e-04,
                         1.5055e-04,  3.7646e-05]],
              
                      [[ 0.0000e+00,  3.7638e-05,  1.5041e-04,  ...,  3.3789e-04,
                         1.5041e-04,  3.7638e-05]],
              
                      ...,
              
                      [[ 0.0000e+00, -3.7638e-05,  1.5041e-04,  ..., -3.3789e-04,
                         1.5041e-04, -3.7638e-05]],
              
                      [[ 0.0000e+00, -3.7646e-05,  1.5055e-04,  ..., -3.3858e-04,
                         1.5055e-04, -3.7646e-05]],
              
                      [[ 0.0000e+00, -3.7649e-05,  1.5059e-04,  ..., -3.3881e-04,
                  

In [11]:
from model.model import Transfer_Cnn14

In [20]:
model = Transfer_Cnn14(
    22050, 
    window_size=512, 
    hop_size=2048, 
    mel_bins=64, 
    fmin=0,
    fmax=48000,
    classes_num=1, 
    freeze_base=False
)

In [21]:
pretrained_path = "/home/hana/sonnh/covidaivn/Cnn14_16k_mAP=0.438.pth"

In [22]:
model.load_from_pretrain(pretrained_path)

In [41]:
from transformers import Wav2Vec2Tokenizer, Wav2Vec2ForCTC
from datasets import load_dataset
import soundfile as sf
import torch

# load model and tokenizer
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

# define function to read in sound file
def map_to_array(batch):
 speech, _ = sf.read(batch["file"])
 batch["speech"] = speech
 return batch

# load dummy dataset and read soundfiles
ds = load_dataset("patrickvonplaten/librispeech_asr_dummy", "clean", split="validation")
ds = ds.map(map_to_array)

# tokenize
input_values = tokenizer(ds["speech"][:2], return_tensors="pt", padding="longest").input_values  # Batch size 1

# retrieve logits
logits = model(input_values).logits

# take argmax and decode
predicted_ids = torch.argmax(logits, dim=-1)
transcription = tokenizer.batch_decode(predicted_ids)

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Reusing dataset librispeech_asr (/home/hana/.cache/huggingface/datasets/librispeech_asr/clean/2.1.0/468ec03677f46a8714ac6b5b64dba02d246a228d92cbbad7f3dc190fa039eab1)
Loading cached processed dataset at /home/hana/.cache/huggingface/datasets/librispeech_asr/clean/2.1.0/468ec03677f46a8714ac6b5b64dba02d246a228d92cbbad7f3dc190fa039eab1/cache-9c5750db106850e1.arrow


In [43]:
import numpy as np

In [44]:
# model.wav2vec2.state_dict()
model_parameters = filter(lambda p: p.requires_grad, model.parameters())
params = sum([np.prod(p.size()) for p in model_parameters])

In [45]:
params

94396320

In [1]:
import torch
import torch.nn as nn
from torch.nn import BCEWithLogitsLoss, CrossEntropyLoss, MSELoss

from transformers.models.wav2vec2.modeling_wav2vec2 import (
    Wav2Vec2PreTrainedModel,
    Wav2Vec2Model
)
from transformers import AutoConfig, Wav2Vec2Processor

class Wav2Vec2ClassificationHead(nn.Module):
    """Head for wav2vec classification task."""

    def __init__(self, config):
        super().__init__()
        self.dense = nn.Linear(config.hidden_size, config.hidden_size)
        self.dropout = nn.Dropout(config.final_dropout)
        self.out_proj = nn.Linear(config.hidden_size, config.num_labels)

    def forward(self, features, **kwargs):
        x = features
        x = self.dropout(x)
        x = self.dense(x)
        x = torch.tanh(x)
        x = self.dropout(x)
        x = self.out_proj(x)
        return x


class Wav2Vec2ForSpeechClassification(Wav2Vec2PreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.pooling_mode = config.pooling_mode
        self.config = config

        self.wav2vec2 = Wav2Vec2Model(config)
        self.classifier = Wav2Vec2ClassificationHead(config)

        self.init_weights()

    def freeze_feature_extractor(self):
        self.wav2vec2.feature_extractor._freeze_parameters()

    def merged_strategy(
            self,
            hidden_states,
            mode="mean"
    ):
        if mode == "mean":
            outputs = torch.mean(hidden_states, dim=1)
        elif mode == "sum":
            outputs = torch.sum(hidden_states, dim=1)
        elif mode == "max":
            outputs = torch.max(hidden_states, dim=1)[0]
        else:
            raise Exception(
                "The pooling method hasn't been defined! Your pooling mode must be one of these ['mean', 'sum', 'max']")

        return outputs

    def forward(
            self,
            input_values,
            attention_mask=None,
            output_attentions=None,
            output_hidden_states=None,
            return_dict=None,
            labels=None,
    ):
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict
        outputs = self.wav2vec2(
            input_values,
            attention_mask=attention_mask,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
        )
        hidden_states = outputs[0]
        hidden_states = self.merged_strategy(hidden_states, mode=self.pooling_mode)
        logits = self.classifier(hidden_states)


        return logits


In [2]:
model_name_or_path = "facebook/wav2vec2-base-960h"
pooling_mode = "mean"
num_labels = 1
# config
config = AutoConfig.from_pretrained(
    model_name_or_path,
    num_labels=num_labels,
    finetuning_task="wav2vec2_clf",
)
setattr(config, 'pooling_mode', pooling_mode)

In [3]:
model = Wav2Vec2ForSpeechClassification.from_pretrained(
    model_name_or_path,
    config=config,
)

model.freeze_feature_extractor()

Some weights of the model checkpoint at facebook/wav2vec2-base-960h were not used when initializing Wav2Vec2ForSpeechClassification: ['lm_head.bias', 'lm_head.weight']
- This IS expected if you are initializing Wav2Vec2ForSpeechClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Wav2Vec2ForSpeechClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Wav2Vec2ForSpeechClassification were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.out_proj.bias', 'wav2vec2.masked_spec_embed', 'classifier.dense.bias']
You should probably TRAIN this model on a

In [49]:
# model.wav2vec2.state_dict()
model_parameters = filter(lambda p: p.requires_grad, model.parameters())
params = sum([np.prod(p.size()) for p in model_parameters])

In [50]:
params

90762625

In [4]:
processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-base-960h")

In [19]:
audio = torch.ones(7 * 16000)

In [20]:
audio.size()

torch.Size([112000])

In [21]:
audio_ = processor(audio, sampling_rate=16000, return_tensors="pt", padding=True).input_values[0]
audio_.size()

torch.Size([112000])

In [22]:
audio_ = processor(audio, sampling_rate=16000, return_tensors="pt", padding='longest').input_values[0]
audio_.size()

torch.Size([112000])

In [35]:
model = model.train()

In [41]:
model(audio_.unsqueeze(0))

tensor([[0.0238]], grad_fn=<AddmmBackward>)

# VGGish

In [73]:
import torch

model = torch.hub.load(
    'harritaylor/torchvggish', 
    'vggish', 
    preprocess = None,
    postprocess = None
)
model.eval()

# Download an example audio file
# import urllib
# url, filename = ("http://soundbible.com/grab.php?id=1698&type=wav", "bus_chatter.wav")
# try: urllib.URLopener().retrieve(url, filename)
# except: urllib.request.urlretrieve(url, filename)

# model.forward(filename)

Using cache found in /home/hana/.cache/torch/hub/harritaylor_torchvggish_master


VGGish(
  (features): Sequential(
    (0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (11): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (12): ReLU(inplace=True)
    (13): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (14): ReLU(inplace=True)
    (15): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False

In [74]:
model.postprocess

In [80]:
filename
import soundfile as sf
# audio, _ = sf.read(filename)
audio, _ = sf.read(filename, dtype='int16')

In [81]:
audio

array([[ 0, -1],
       [ 1,  1],
       [ 0,  0],
       ...,
       [ 2,  1],
       [-2, -1],
       [ 0,  1]], dtype=int16)

In [76]:
audio.shape

(807843, 2)

In [67]:
audio

array([[ 0.00000000e+00, -3.05175781e-05],
       [ 3.05175781e-05,  3.05175781e-05],
       [ 0.00000000e+00,  0.00000000e+00],
       ...,
       [ 6.10351562e-05,  3.05175781e-05],
       [-6.10351562e-05, -3.05175781e-05],
       [ 0.00000000e+00,  3.05175781e-05]])

In [77]:
audio_ = torch.tensor(audio[:, 0])

In [63]:
audio_.size()

torch.Size([807843, 2])

In [78]:
x = model(audio_)

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 1, 3, 3], but got 1-dimensional input of size [807843] instead

In [45]:
x.size()

torch.Size([19, 128])

In [46]:
model

VGGish(
  (features): Sequential(
    (0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (11): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (12): ReLU(inplace=True)
    (13): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (14): ReLU(inplace=True)
    (15): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False

In [48]:
import numpy as np
model_parameters = filter(lambda p: p.requires_grad, model.parameters())
params = sum([np.prod(p.size()) for p in model_parameters])

In [49]:
params

72141184